dj - rewrote workflow to run on fail

diff --git a/.github/workflows/16-backend-autoformat.yml b/.github/workflows/16-backend-autoformat.yml
--- a/.github/workflows/16-backend-autoformat.yml
+++ b/.github/workflows/16-backend-autoformat.yml
@@ -27,19 +27,22 @@ jobs:
           cache-dependency-path: 'pom.xml'
 
       - name: Check formatting with Maven
-        run: mvn -ntp git-code-format:validate-code-format
+        id: format-check
+        run: |
+          mvn -ntp git-code-format:validate-code-format && echo "FORMAT_REQUIRED=false" >> $GITHUB_OUTPUT || echo "FORMAT_REQUIRED=true" >> $GITHUB_OUTPUT
 
-      - name: "IF STEP ABOVE FAILS ^^^ you need: mvn -ntp git-code-format:format-code"
+      - name: Run Format if failed
         id: format-step
-        if: failure() # Only run if the previous step failed
+        if: ${{ steps.format-check.outputs.FORMAT_REQUIRED }} == true  # Only run if the previous step failed
         run: |
           mvn git-code-format:format-code
-          CHANGED_FILES=$(git diff --name-only HEAD --- src/)
+          CHANGED_FILES=$(git diff --name-only HEAD -- src/)
           CHANGED_FILES_STRING=$(echo "$CHANGED_FILES" | tr '\n' ' ' | sed 's/ $//')
           echo "files=$CHANGED_FILES_STRING" >> $GITHUB_OUTPUT
 
       - name: Commit changes
         uses: pirafrank/github-commit-sign@v0
+        if: ${{ steps.format-check.outputs.FORMAT_REQUIRED }} == true
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           CHANGED_FILES: ${{ steps.format-step.outputs.files }}
